name: WakaTime Readme

on:
  schedule:
    - cron: "30 18 * * *"
  push:
    branches:
      - "**"

jobs:
  waka_waka_job:
    runs-on: ubuntu-latest
    name: A job to update Wakatime stats in README.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: WakaWaka Action
        uses: aayush-goyal/wakawaka-action@v1.2.3

        with:
          COMMIT_EMAIL: "aayushgoyal.mps@gmail.com"
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_WORKSPACE: ${{ github.workspace }}
          WAKA_AUTH_TOKEN: ${{ secrets.WAKATIME_API_KEY }}
          WAKA_USERNAME: "aayushgoyalmps"
