name: WakaTime Readme

on:
  [push]
  # schedule:
  #   - cron: "30 18 * * *"
  # workflow_dispatch:

jobs:
  # update-readme:
  #   name: Update Readme with Metrics
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: anmol098/waka-readme-stats@master
  #       with:
  #         COMMIT_BY_ME: "False"
  #         COMMIT_MESSAGE: "Updated dev metrics"
  #         COMMIT_USERNAME: "aayush-goyal"
  #         COMMIT_EMAIL: "aayushgoyal.mps@gmail.com"
  #         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         SHOW_COMMIT: "True"
  #         SHOW_DAYS_OF_WEEK: "False"
  #         SHOW_EDITORS: "False"
  #         SHOW_LANGUAGE: "True"
  #         SHOW_LANGUAGE_PER_REPO: "True"
  #         SHOW_LINES_OF_CODE: "True"
  #         SHOW_LOC_CHART: "True"
  #         SHOW_OS: "False"
  #         SHOW_PROFILE_VIEWS: "False"
  #         SHOW_PROJECTS: "True"
  #         SHOW_SHORT_INFO: "True"
  #         SHOW_UPDATED_DATE: "True"
  waka_waka_job:
    runs-on: ubuntu-latest
    name: A job to update Wakatime stats in README.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: aayush-goyal/wakawaka-action
        with:
          COMMIT_EMAIL: "aayushgoyal.mps@gmail.com"
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_WORKSPACE: ${{ github.workspace }}
          WAKA_AUTH_TOKEN: ${{ secrets.WAKATIME_API_KEY }}
